# Generated by Django 2.0.1 on 2018-01-12 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_ov', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShowingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showing_dates', to='core.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Starmovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Regau', 'Regau'), ('Liezen', 'Liezen'), ('Peuerbach', 'Peuerbach'), ('Ried', 'Ried'), ('Steyr', 'Steyr'), ('Wels', 'Wels')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_alert_emails', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User settings',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='locations',
            field=models.ManyToManyField(related_name='movies', to='core.Starmovie'),
        ),
    ]
